---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: xnamespaces.justinsb.com
spec:
  group: justinsb.com
  names:
    kind: XNamespace
    listKind: XNamespaceList
    plural: xnamespaces
    singular: xnamespace
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: CompositeDefinition is the Schema for the compositedefinitions
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CompositeDefinitionSpec defines the desired state of CompositeDefinition
            properties:
              #machineType:
              #  description: 'Channel specifies a channel that can be used to resolve
              #    a specific addon, eg: stable It will be ignored if Version is specified'
              #  type: string
            type: object
          status:
            description: CompositeDefinitionStatus defines the observed state of CompositeDefinition
            properties:
              errors:
                items:
                  type: string
                type: array
              healthy:
                type: boolean
              phase:
                type: string
            required:
            - healthy
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
